<a href="https://colab.research.google.com/github/AditiSinghal28/Machine-Learning-Projects/blob/ml/Credit_Card_Fraud_Detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IMPORTING THE DEPENDENCIES

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

DATA COLLECTION AND PREPROCESSING

In [2]:
# loading dataset into dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [3]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [7]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [4]:
credit_card_data.shape

(284807, 31)

In [5]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [6]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

Class : 0 --> legit
        1 --> fraud

In [8]:
# checking the distribution of class
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This dataset is highly unbalanced

In [9]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [10]:
legit.shape

(284315, 31)

In [11]:
fraud.shape

(492, 31)

In [12]:
# statistical measures of data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [13]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [14]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

UNDERSAMPLING

Build a sample dataset containing similar distribution of normal(legit) transactions and fraudulent transactions

Number of fraud transactions = 492

In [16]:
# we are going to take 492 samples of legit transactions from all the legit transactions
# and create a new dataset with 492 legit and 492 frud transactions

In [17]:
legit_sample = legit.sample(492) # or legit.sample(n= 492)

In [18]:
legit_sample.shape

(492, 31)

Concatenating two dataframes

In [19]:
new_dataset = pd.concat([legit_sample, fraud], axis = 0) # axis = 0 means we are joining them row wise

In [20]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
43638,41589.0,0.933366,-0.455680,-1.352368,0.201735,2.041059,3.426195,-0.153745,0.756071,-0.211061,...,-0.118567,-0.901116,-0.148216,0.975348,0.558951,-0.540405,-0.014563,0.051314,186.90,0
257053,157981.0,0.206061,0.807816,0.769808,2.411073,-0.091758,-0.776407,0.572877,-0.187751,-0.358332,...,0.389943,1.470053,-0.071534,0.917086,-0.753175,-0.116267,0.315514,0.252122,10.00,0
32044,36618.0,1.215816,-0.357380,0.580201,-1.422462,-1.054596,-1.104801,-0.329252,-0.082040,1.072248,...,-0.075582,-0.191969,0.075951,0.558563,0.210717,-0.182475,0.008615,0.017870,20.00,0
212275,138794.0,1.556636,-0.858618,-1.541472,1.235769,0.142803,0.172018,0.186438,-0.093988,0.434570,...,0.536618,1.219162,-0.459225,-0.981304,0.427739,-0.227500,-0.026433,-0.027460,250.00,0
52341,45398.0,0.198239,-2.717672,0.292884,0.018575,-1.883743,0.212031,-0.265949,-0.115573,-0.015025,...,0.346015,-0.176621,-0.607378,-0.058724,0.256154,-0.279064,-0.057332,0.127993,621.36,0

In [21]:
new_dataset.shape

(984, 31)

In [22]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [23]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [24]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,92443.363821,-0.066341,-0.152819,-0.021455,0.058922,-0.020971,-0.002437,-0.055693,-0.042205,0.053739,...,-0.009300,-0.011276,-0.030482,0.036838,0.026876,-0.030485,-0.000003,-0.001710,0.018406,91.582236
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [26]:
new_dataset.info()

<class 'pandas.core.frame.DataFrame'>
Index: 984 entries, 43638 to 281674
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    984 non-null    float64
 1   V1      984 non-null    float64
 2   V2      984 non-null    float64
 3   V3      984 non-null    float64
 4   V4      984 non-null    float64
 5   V5      984 non-null    float64
 6   V6      984 non-null    float64
 7   V7      984 non-null    float64
 8   V8      984 non-null    float64
 9   V9      984 non-null    float64
 10  V10     984 non-null    float64
 11  V11     984 non-null    float64
 12  V12     984 non-null    float64
 13  V13     984 non-null    float64
 14  V14     984 non-null    float64
 15  V15     984 non-null    float64
 16  V16     984 non-null    float64
 17  V17     984 non-null    float64
 18  V18     984 non-null    float64
 19  V19     984 non-null    float64
 20  V20     984 non-null    float64
 21  V21     984 non-null    float64
 22  V22     984 non-null    float64
 23  V23     984 non-null    float64
 24  V24     984 non-null    float64
 25  V25     984 non-null    float64
 26  V26     984 non-null    float64
 27  V27     984 non-null    float64
 28  V28     984 non-null    float64
 29  Amount  984 non-null    float64
 30  Class   984 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 246.0 KB

In [27]:
new_dataset.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,...,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000,984.000000
mean,86595.085366,-2.419145,1.735480,-3.527368,2.300476,-1.586098,-0.700087,-2.812212,0.264215,-1.263692,...,0.351156,-0.008216,-0.001735,-0.039127,0.005482,0.025822,0.084433,0.047037,106.896778,0.500000
std,48374.946642,5.600144,3.934566,6.214123,3.186428,4.274583,1.818495,5.867916,4.896213,2.331200,...,2.806580,1.171981,1.167617,0.572817,0.676682,0.488469,1.051791,0.662987,251.518271,0.500254
min,98.000000,-30.552380,-37.154221,-31.103685,-4.407691,-22.105532,-12.709475,-43.557242,-41.044261,-13.434066,...,-22.797604,-8.887017,-19.254328,-2.028024,-4.781606,-1.357533,-9.845808,-4.601959,0.000000,0.000000
25%,43552.500000,-2.958336,-0.211518,-5.120349,-0.004082,-1.901986,-1.572753,-3.152655,-0.220907,-2.327661,...,-0.177660,-0.551085,-0.236098,-0.415078,-0.316148,-0.294272,-0.061168,-0.059310,1.490000,0.000000
50%,79986.500000,-0.813153,0.962865,-1.349259,1.347057,-0.485067,-0.668527,-0.715752,0.146901,-0.688718,...,0.134861,0.013316,-0.012281,0.012664,0.056850,-0.011590,0.055450,0.034645,17.970000,0.500000
75%,134224.500000,1.079784,2.793742,0.299178,4.235631,0.457344,0.115658,0.247216,0.877002,0.198826,...,0.655130,0.567301,0.207068,0.388798,0.380408,0.322613,0.454884,0.219773,99.990000,1.000000
max,171063.000000,2.300331,22.057729,3.757300,12.114672,14.929359,6.474115,10.371581,20.007208,4.899194,...,27.202839,8.361985,5.466230,1.305978,2.208209,2.745261,3.052358,15.407019,2663.070000,1.000000

SPLITTING THE DATASET INTO FEATURES AND TARGET

In [28]:
X = new_dataset.drop(columns = 'Class', axis = 1)
Y = new_dataset['Class']

In [29]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
43638    41589.0  0.933366 -0.455680 -1.352368  0.201735  2.041059  3.426195
257053  157981.0  0.206061  0.807816  0.769808  2.411073 -0.091758 -0.776407
32044    36618.0  1.215816 -0.357380  0.580201 -1.422462 -1.054596 -1.104801
212275  138794.0  1.556636 -0.858618 -1.541472  1.235769  0.142803  0.172018
52341    45398.0  0.198239 -2.717672  0.292884  0.018575 -1.883743  0.212031
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
43638  -0.153745  0.756071 -0.211061  ...  0.352796 -0.118567 -0.901116
257053  0.572877 -0.187751 -0.358332  ...  0.075003  0.389943  1.470053
32044  -0.329252 -0.082040  1.072248  ... -0.025194 -0.075582 -0.191969
212275  0.186438 -0.093988  0.434570  ...  0.270999  0.536618  1.219162
52341  -0.265949 -0.115573 -0.015025  ...  1.359496  0.346015 -0.176621
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
43638  -0.148216  0.975348  0.558951 -0.540405 -0.014563  0.051314  186.90
257053 -0.071534  0.917086 -0.753175 -0.116267  0.315514  0.252122   10.00
32044   0.075951  0.558563  0.210717 -0.182475  0.008615  0.017870   20.00
212275 -0.459225 -0.981304  0.427739 -0.227500 -0.026433 -0.027460  250.00
52341  -0.607378 -0.058724  0.256154 -0.279064 -0.057332  0.127993  621.36
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [30]:
print(Y)

43638     0
257053    0
32044     0
212275    0
52341     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

SPLITTING THE DATASET INTO TRAINING AND TEST DATA

In [31]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2)

In [32]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

MODEL TRAINING

In [33]:
model = LogisticRegression()

In [34]:
model.fit(X_train, Y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

EVALUATION

In [35]:
# accuracy score of training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [36]:
print('Accuracy on training data : ', training_data_accuracy)

Accuracy on training data :  0.9351969504447268

In [37]:
# accuracy score of test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [38]:
print('Accuracy on test data : ', test_data_accuracy)

Accuracy on test data :  0.9390862944162437

BUILDING A PREDICTIVE MODEL

In [40]:
input_data = (10,1.44904378114715,-1.17633882535966,0.913859832832795,-1.37566665499943,-1.97138316545323,-0.62915213889734,-1.4232356010359,0.0484558879088564,-1.72040839292037,1.62665905834133,1.1996439495421,-0.671439778462005,-0.513947152539479,-0.0950450453999549,0.230930409124119,0.0319674667862076,0.253414715863197,0.854343814324194,-0.221365413645481,-0.387226474431156,-0.00930189652490052,0.313894410791098,0.0277401580170247,0.500512287104917,0.25136735874921,-0.129477953726618,0.0428498709381461,0.0162532619375515,7.8)
input_data_as_numpy_array = np.asarray(input_data)
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0] == 0):
  print('The transaction is legit')
else:
  print('The transaction is fraud')

[0]
The transaction is legit

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(